apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: guestbook:v2
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: http
        resources:
          limits:
            cpu: 5m
            memory: 128Mi
          requests:
            cpu: 2m
            memory: 64Mi
